--[[
	File: AuspexHelper_data.lua
	Description: DMF settings for Aspex Helper.
	Overall Release Version: 1.0.0
	File Version: 1.0.0
	File Introduced in: 1.0.0
	Last Updated: 2026-03-14
	Author: LAUREHTE
]]

local mod = get_mod("AuspexHelper")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "enable_group",
				type = "group",
				title = "enable_group",
				tooltip = "enable_group_desc",
				sub_widgets = {
					{
						setting_id = "enable_mod_override",
						type = "checkbox",
						default_value = true,
						title = "enable_mod_override",
						tooltip = "enable_mod_override_desc",
					},
					{
						setting_id = "enable_world_scans",
						type = "checkbox",
						default_value = true,
						title = "enable_world_scans",
						tooltip = "enable_world_scans_desc",
					},
					{
						setting_id = "enable_scanner_visibility",
						type = "checkbox",
						default_value = false,
						title = "enable_scanner_visibility",
						tooltip = "enable_scanner_visibility_desc",
					},
					{
						setting_id = "enable_decode_minigame",
						type = "checkbox",
						default_value = true,
						title = "enable_decode_minigame",
						tooltip = "enable_decode_minigame_desc",
					},
					{
						setting_id = "enable_drill_minigame",
						type = "checkbox",
						default_value = true,
						title = "enable_drill_minigame",
						tooltip = "enable_drill_minigame_desc",
					},
					{
						setting_id = "enable_frequency_minigame",
						type = "checkbox",
						default_value = true,
						title = "enable_frequency_minigame",
						tooltip = "enable_frequency_minigame_desc",
					},
					{
						setting_id = "enable_balance_minigame",
						type = "checkbox",
						default_value = true,
						title = "enable_balance_minigame",
						tooltip = "enable_balance_minigame_desc",
					},
					{
						setting_id = "enable_expedition_minigame",
						type = "checkbox",
						default_value = true,
						title = "enable_expedition_minigame",
						tooltip = "enable_expedition_minigame_desc",
					},
					{
						setting_id = "enable_preview",
						type = "checkbox",
						default_value = true,
						title = "enable_preview",
						tooltip = "enable_preview_desc",
					},
				},
			},
			{
				setting_id = "preview_group",
				type = "group",
				title = "preview_group",
				tooltip = "preview_group_desc",
				sub_widgets = {
					{
						setting_id = "preview_type",
						type = "dropdown",
						default_value = "decode_symbols",
						title = "preview_type",
						tooltip = "preview_type_desc",
						options = {
							{ text = "preview_type_decode_symbols", value = "decode_symbols" },
							{ text = "preview_type_decode_symbols_12", value = "decode_symbols_12" },
							{ text = "preview_type_drill", value = "drill" },
							{ text = "preview_type_frequency", value = "frequency" },
							{ text = "preview_type_balance", value = "balance" },
							{ text = "preview_type_expedition", value = "scan" },
						},
					},
					{
						setting_id = "toggle_preview_key",
						type = "keybind",
						default_value = { "f8" },
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "toggle_preview",
						title = "toggle_preview_key",
						tooltip = "toggle_preview_key_desc",
					},
					{
						setting_id = "practice_balance_time_multiplier",
						type = "numeric",
						default_value = 3,
						range = { 1, 10 },
						decimals_number = 2,
						step_size_value = 0.25,
						title = "practice_balance_time_multiplier",
						tooltip = "practice_balance_time_multiplier_desc",
					},
					{
						setting_id = "practice_decode_speed_multiplier",
						type = "numeric",
						default_value = 1,
						range = { 0.5, 3 },
						decimals_number = 2,
						step_size_value = 0.1,
						title = "practice_decode_speed_multiplier",
						tooltip = "practice_decode_speed_multiplier_desc",
					},
					{
						setting_id = "practice_balance_difficulty",
						type = "numeric",
						default_value = 1,
						range = { 0.5, 3 },
						decimals_number = 2,
						step_size_value = 0.1,
						title = "practice_balance_difficulty",
						tooltip = "practice_balance_difficulty_desc",
					},
				},
			},
			{
				setting_id = "world_scan_group",
				type = "group",
				title = "world_scan_group",
				tooltip = "world_scan_group_desc",
				sub_widgets = {
					{
						setting_id = "world_scan_display_mode",
						type = "dropdown",
						default_value = "both",
						title = "world_scan_display_mode",
						tooltip = "world_scan_display_mode_desc",
						options = {
							{ text = "world_scan_display_mode_highlight", value = "highlight" },
							{ text = "world_scan_display_mode_icon", value = "icon" },
							{ text = "world_scan_display_mode_both", value = "both" },
						},
					},
					{
						setting_id = "world_scan_always_show",
						type = "checkbox",
						default_value = true,
						title = "world_scan_always_show",
						tooltip = "world_scan_always_show_desc",
					},
					{
						setting_id = "world_scan_through_walls",
						type = "checkbox",
						default_value = false,
						title = "world_scan_through_walls",
						tooltip = "world_scan_through_walls_desc",
					},
					{
						setting_id = "world_scan_item_overlay",
						type = "checkbox",
						default_value = true,
						title = "world_scan_item_overlay",
						tooltip = "world_scan_item_overlay_desc",
					},
					{
						setting_id = "world_scan_color_red",
						type = "numeric",
						default_value = 0,
						range = { 0, 255 },
						decimals_number = 0,
						title = "world_scan_color_red",
						tooltip = "world_scan_color_red_desc",
					},
					{
						setting_id = "world_scan_color_green",
						type = "numeric",
						default_value = 255,
						range = { 0, 255 },
						decimals_number = 0,
						title = "world_scan_color_green",
						tooltip = "world_scan_color_green_desc",
					},
					{
						setting_id = "world_scan_color_blue",
						type = "numeric",
						default_value = 110,
						range = { 0, 255 },
						decimals_number = 0,
						title = "world_scan_color_blue",
						tooltip = "world_scan_color_blue_desc",
					},
					{
						setting_id = "world_scan_color_alpha",
						type = "numeric",
						default_value = 255,
						range = { 0, 255 },
						decimals_number = 0,
						title = "world_scan_color_alpha",
						tooltip = "world_scan_color_alpha_desc",
					},
				},
			},
			{
				setting_id = "scanner_view_group",
				type = "group",
				title = "scanner_view_group",
				tooltip = "scanner_view_group_desc",
				sub_widgets = {
					{
						setting_id = "live_display_mode",
						type = "dropdown",
						default_value = "overlay",
						title = "live_display_mode",
						tooltip = "live_display_mode_desc",
						options = {
							{ text = "display_mode_item", value = "item" },
							{ text = "display_mode_overlay", value = "overlay" },
						},
					},
					{
						setting_id = "overlay_display_scale",
						type = "numeric",
						range = { 0.1, 2 },
						default_value =0.4,
						decimals_number = 1,
						step_size_value = 0.1,
						title = "overlay_display_scale",
						tooltip = "overlay_display_scale_desc",
					},
					{
						setting_id = "overlay_background_opacity",
						type = "numeric",
						range = { 0, 255 },
						default_value = 200,
						decimals_number = 0,
						title = "overlay_background_opacity",
						tooltip = "overlay_background_opacity_desc",
					},
					{
						setting_id = "overlay_color_red",
						type = "numeric",
						default_value = 10,
						range = { 0, 255 },
						decimals_number = 0,
						title = "overlay_color_red",
						tooltip = "overlay_color_red_desc",
					},
					{
						setting_id = "overlay_color_green",
						type = "numeric",
						default_value = 255,
						range = { 0, 225 },
						decimals_number = 0,
						title = "overlay_color_green",
						tooltip = "overlay_color_green_desc",
					},
					{
						setting_id = "overlay_color_blue",
						type = "numeric",
						default_value = 110,
						range = { 0, 225 },
						decimals_number = 0,
						title = "overlay_color_blue",
						tooltip = "overlay_color_blue_desc",
					},
					{
						setting_id = "overlay_color_alpha",
						type = "numeric",
						default_value = 255,
						range = { 0, 255 },
						decimals_number = 0,
						title = "overlay_color_alpha",
						tooltip = "overlay_color_alpha_desc",
					},
					{
						setting_id = "overlay_show_decorations",
						type = "checkbox",
						default_value = false,
						title = "overlay_show_decorations",
						tooltip = "overlay_show_decorations_desc",
					},
					{
						setting_id = "scanner_transparency_amount",
						type = "numeric",
						range = { 0, 1 },
						default_value = 0.2,
						decimals_number = 2,
						step_size_value = 0.05,
						title = "scanner_transparency_amount",
						tooltip = "scanner_transparency_amount_desc",
					},
					{
						setting_id = "scanner_smooth_fade",
						type = "checkbox",
						default_value = true,
						title = "scanner_smooth_fade",
						tooltip = "scanner_smooth_fade_desc",
					},
					{
						setting_id = "scanner_fade_duration",
						type = "numeric",
						range = { 0.05, 2 },
						default_value = 0.5,
						decimals_number = 2,
						step_size_value = 0.05,
						title = "scanner_fade_duration",
						tooltip = "scanner_fade_duration_desc",
					},
					{
						setting_id = "scanner_caption_opacity",
						type = "numeric",
						range = { 0, 1 },
						default_value = 0.2,
						decimals_number = 2,
						step_size_value = 0.01,
						title = "scanner_caption_opacity",
						tooltip = "scanner_caption_opacity_desc",
					},
					{
						setting_id = "scanner_hide_crosshair",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_crosshair",
						tooltip = "scanner_hide_crosshair_desc",
					},
					{
						setting_id = "scanner_hide_crosshair_hud",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_crosshair_hud",
						tooltip = "scanner_hide_crosshair_hud_desc",
					},
					{
						setting_id = "scanner_hide_dodge_counter",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_dodge_counter",
						tooltip = "scanner_hide_dodge_counter_desc",
					},
					{
						setting_id = "scanner_hide_dodge_count",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_dodge_count",
						tooltip = "scanner_hide_dodge_count_desc",
					},
					{
						setting_id = "scanner_hide_stamina",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_stamina",
						tooltip = "scanner_hide_stamina_desc",
					},
					{
						setting_id = "scanner_hide_ability_icons",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_ability_icons",
						tooltip = "scanner_hide_ability_icons_desc",
					},
					{
						setting_id = "scanner_hide_buff_bars",
						type = "checkbox",
						default_value = true,
						title = "scanner_hide_buff_bars",
						tooltip = "scanner_hide_buff_bars_desc",
					},
				},
			},
			{
				setting_id = "decode_group",
				type = "group",
				title = "decode_group",
				tooltip = "decode_group_desc",
				sub_widgets = {
					{
						setting_id = "enable_decode_helper",
						type = "checkbox",
						default_value = true,
						title = "enable_decode_helper",
						tooltip = "enable_decode_helper_desc",
					},
					{
						setting_id = "enable_decode_autosolve",
						type = "checkbox",
						default_value = false,
						title = "enable_decode_autosolve",
						tooltip = "enable_decode_autosolve_desc",
					},
					{
						setting_id = "decode_interact_cooldown",
						type = "numeric",
						default_value = 150,
						range = { 20, 300 },
						decimals_number = 0,
						title = "decode_interact_cooldown",
						tooltip = "decode_interact_cooldown_desc",
					},
					{
						setting_id = "decode_target_precision",
						type = "numeric",
						default_value = 4,
						range = { 1, 4 },
						decimals_number = 0,
						title = "decode_target_precision",
						tooltip = "decode_target_precision_desc",
					},
					{
						setting_id = "decode_future_rows",
						type = "dropdown",
						default_value = 3,
						title = "decode_future_rows",
						tooltip = "decode_future_rows_desc",
						options = {
							{ text = "future_rows_0", value = 0 },
							{ text = "future_rows_1", value = 1 },
							{ text = "future_rows_2", value = 2 },
							{ text = "future_rows_3", value = 3 },
						},
					},
				},
			},
			{
				setting_id = "drill_group",
				type = "group",
				title = "drill_group",
				tooltip = "drill_group_desc",
				sub_widgets = {
					{
						setting_id = "enable_drill_helper",
						type = "checkbox",
						default_value = true,
						title = "enable_drill_helper",
						tooltip = "enable_drill_helper_desc",
					},
					{
						setting_id = "enable_drill_autosolve",
						type = "checkbox",
						default_value = false,
						title = "enable_drill_autosolve",
						tooltip = "enable_drill_autosolve_desc",
					},
					{
						setting_id = "drill_autosolve_speed",
						type = "numeric",
						default_value = 0.3,
						range = { 0.05, 2 },
						decimals_number = 2,
						step_size_value = 0.05,
						title = "drill_autosolve_speed",
						tooltip = "drill_autosolve_speed_desc",
					},
					{
						setting_id = "enable_drill_direction_arrows",
						type = "checkbox",
						default_value = true,
						title = "enable_drill_direction_arrows",
						tooltip = "enable_drill_direction_arrows_desc",
					},
					{
						setting_id = "enable_drill_overlay_sonar",
						type = "checkbox",
						default_value = false,
						title = "enable_drill_overlay_sonar",
						tooltip = "enable_drill_overlay_sonar_desc",
					},
				},
			},
			{
				setting_id = "frequency_group",
				type = "group",
				title = "frequency_group",
				tooltip = "frequency_group_desc",
				sub_widgets = {
					{
						setting_id = "enable_frequency_autosolve",
						type = "checkbox",
						default_value = false,
						title = "enable_frequency_autosolve",
						tooltip = "enable_frequency_autosolve_desc",
					},
					{
						setting_id = "frequency_autosolve_strength",
						type = "numeric",
						default_value = 0.2,
						range = { 0.05, 2 },
						decimals_number = 2,
						step_size_value = 0.05,
						title = "frequency_autosolve_strength",
						tooltip = "frequency_autosolve_strength_desc",
					},
				},
			},
			{
				setting_id = "balance_group",
				type = "group",
				title = "balance_group",
				tooltip = "balance_group_desc",
				sub_widgets = {
					{
						setting_id = "enable_balance_autosolve",
						type = "checkbox",
						default_value = false,
						title = "enable_balance_autosolve",
						tooltip = "enable_balance_autosolve_desc",
					},
					{
						setting_id = "balance_autosolve_strength",
						type = "numeric",
						default_value = 0.2,
						range = { 0.1, 3 },
						decimals_number = 1,
						title = "balance_autosolve_strength",
						tooltip = "balance_autosolve_strength_desc",
					},
				},
			},
			{
				setting_id = "ui_color_group",
				type = "group",
				title = "ui_color_group",
				tooltip = "ui_color_group_desc",
				sub_widgets = {
					{
						setting_id = "ui_color_red",
						type = "numeric",
						default_value = 255,
						range = { 0, 255 },
						decimals_number = 0,
						title = "ui_color_red",
						tooltip = "ui_color_red_desc",
					},
					{
						setting_id = "ui_color_green",
						type = "numeric",
						default_value = 115,
						range = { 0, 255 },
						decimals_number = 0,
						title = "ui_color_green",
						tooltip = "ui_color_green_desc",
					},
					{
						setting_id = "ui_color_blue",
						type = "numeric",
						default_value = 0,
						range = { 0, 255 },
						decimals_number = 0,
						title = "ui_color_blue",
						tooltip = "ui_color_blue_desc",
					},
					{
						setting_id = "ui_color_alpha",
						type = "numeric",
						default_value = 210,
						range = { 0, 255 },
						decimals_number = 0,
						title = "ui_color_alpha",
						tooltip = "ui_color_alpha_desc",
					},
				},
			},
		},
	},
}
