local mod = get_mod("ElevatorMusic")

return {
    name = "ElevatorMusic",
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "elevatormusic_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_enable",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_enable",
                        tooltip = "elevatormusic_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_play_activation",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_play_activation",
                        tooltip = "elevatormusic_play_activation_desc",
                    },
                    {
                        setting_id = "elevatormusic_activation_linger",
                        type = "numeric",
                        default_value = 3,
                        range = { 0, 20 },
                        decimals_number = 0,
                        title = "elevatormusic_activation_linger",
                        tooltip = "elevatormusic_activation_linger_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_enabled",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_idle_enabled",
                        tooltip = "elevatormusic_idle_enabled_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_after_activation",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_idle_after_activation",
                        tooltip = "elevatormusic_idle_after_activation_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_distance",
                        type = "numeric",
                        default_value = 10,
                        range = { 4, 50 },
                        decimals_number = 0,
                        title = "elevatormusic_idle_distance",
                        tooltip = "elevatormusic_idle_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_full_distance",
                        type = "numeric",
                        default_value = 4,
                        range = { 0.5, 50 },
                        decimals_number = 2,
                        title = "elevatormusic_idle_full_distance",
                        tooltip = "elevatormusic_idle_full_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_random_order",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_random_order",
                        tooltip = "elevatormusic_random_order_desc",
                    },
                    {
                        setting_id = "elevatormusic_volume_percent",
                        type = "numeric",
                        default_value = 120,
                        range = { 10, 300 },
                        decimals_number = 0,
                        title = "elevatormusic_volume_percent",
                        tooltip = "elevatormusic_volume_percent_desc",
                    },
                    {
                        setting_id = "elevatormusic_fade_seconds",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 0, 6 },
                        decimals_number = 1,
                        title = "elevatormusic_fade_seconds",
                        tooltip = "elevatormusic_fade_seconds_desc",
                    },
                    {
                        setting_id = "elevatormusic_spatial_rolloff",
                        type = "dropdown",
                        default_value = "linear",
                        options = {
                            { text = "elevatormusic_spatial_rolloff_linear", value = "linear" },
                            { text = "elevatormusic_spatial_rolloff_log", value = "logarithmic" },
                        },
                        title = "elevatormusic_spatial_rolloff",
                        tooltip = "elevatormusic_spatial_rolloff_desc",
                    },
                    {
                        setting_id = "elevatormusic_show_markers",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_show_markers",
                        tooltip = "elevatormusic_show_markers_desc",
                    },
                    {
                        setting_id = "elevatormusic_test_emitter",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_test_emitter",
                        tooltip = "elevatormusic_test_emitter_desc",
                    },
                    {
                        setting_id = "elevatormusic_debug",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_debug",
                        tooltip = "elevatormusic_debug_desc",
                    },
                },
            },
            {
                setting_id = "elevatormusic_visuals_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_debug_audio",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_debug_audio",
                        tooltip = "elevatormusic_debug_audio_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_enable",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_visuals_enable",
                        tooltip = "elevatormusic_visuals_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_speed",
                        type = "numeric",
                        default_value = 1.2,
                        range = { 0.1, 12.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_speed",
                        tooltip = "elevatormusic_visuals_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_randomness",
                        type = "numeric",
                        default_value = 0.3,
                        range = { 0, 5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_randomness",
                        tooltip = "elevatormusic_visuals_randomness_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_halo_count",
                        type = "numeric",
                        default_value = 1,
                        range = { 1, 6 },
                        decimals_number = 0,
                        title = "elevatormusic_visuals_halo_count",
                        tooltip = "elevatormusic_visuals_halo_count_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_radius_min",
                        type = "numeric",
                        default_value = 0.45,
                        range = { 0.2, 5.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_radius_min",
                        tooltip = "elevatormusic_visuals_radius_min_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_radius_max",
                        type = "numeric",
                        default_value = 0.75,
                        range = { 0.2, 5.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_radius_max",
                        tooltip = "elevatormusic_visuals_radius_max_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_count",
                        type = "numeric",
                        default_value = 16,
                        range = { 4, 48 },
                        decimals_number = 0,
                        title = "elevatormusic_visuals_light_count",
                        tooltip = "elevatormusic_visuals_light_count_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_orbit_variance",
                        type = "numeric",
                        default_value = 0.4,
                        range = { 0, 2 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_light_orbit_variance",
                        tooltip = "elevatormusic_visuals_light_orbit_variance_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_vertical_variance",
                        type = "numeric",
                        default_value = 0.6,
                        range = { 0, 4 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_light_vertical_variance",
                        tooltip = "elevatormusic_visuals_light_vertical_variance_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_loop_speed",
                        type = "numeric",
                        default_value = 1.2,
                        range = { 0, 10 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_loop_speed",
                        tooltip = "elevatormusic_visuals_loop_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_spin_randomness",
                        type = "numeric",
                        default_value = 0.5,
                        range = { 0, 5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_spin_randomness",
                        tooltip = "elevatormusic_visuals_spin_randomness_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_show_core",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_visuals_show_core",
                        tooltip = "elevatormusic_visuals_show_core_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_orbit_radius",
                        type = "numeric",
                        default_value = 0.25,
                        range = { 0, 2.5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_orbit_radius",
                        tooltip = "elevatormusic_visuals_orbit_radius_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_orbit_speed",
                        type = "numeric",
                        default_value = 1.0,
                        range = { 0, 10 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_orbit_speed",
                        tooltip = "elevatormusic_visuals_orbit_speed_desc",
                    },
                },
            },
        },
    },
}
