local mod = get_mod("ElevatorMusic")

return {
    name = "ElevatorMusic",
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "elevatormusic_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_enable",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_enable",
                        tooltip = "elevatormusic_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_valk_enable",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_valk_enable",
                        tooltip = "elevatormusic_valk_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_valk_idle_distance",
                        type = "numeric",
                        default_value = 45,
                        range = { 10, 80 },
                        decimals_number = 0,
                        title = "elevatormusic_valk_idle_distance",
                        tooltip = "elevatormusic_valk_idle_distance_desc",
                        show_widget_condition = { setting_id = "elevatormusic_valk_enable", value = true },
                    },
                    {
                        setting_id = "elevatormusic_valk_idle_full_distance",
                        type = "numeric",
                        default_value = 8,
                        range = { 1, 50 },
                        decimals_number = 1,
                        title = "elevatormusic_valk_idle_full_distance",
                        tooltip = "elevatormusic_valk_idle_full_distance_desc",
                        show_widget_condition = { setting_id = "elevatormusic_valk_enable", value = true },
                    },
                    {
                        setting_id = "elevatormusic_activation_only",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_activation_only",
                        tooltip = "elevatormusic_activation_only_desc",
                    },
                    {
                        setting_id = "elevatormusic_activation_linger",
                        type = "numeric",
                        default_value = 3,
                        range = { 0, 20 },
                        decimals_number = 0,
                        title = "elevatormusic_activation_linger",
                        tooltip = "elevatormusic_activation_linger_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_after_activation",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_idle_after_activation",
                        tooltip = "elevatormusic_idle_after_activation_desc",
                    },
                    {
                        setting_id = "elevatormusic_shuffle_on_end",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_shuffle_on_end",
                        tooltip = "elevatormusic_shuffle_on_end_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_distance",
                        type = "numeric",
                        default_value = 30,
                        range = { 4, 50 },
                        decimals_number = 0,
                        title = "elevatormusic_idle_distance",
                        tooltip = "elevatormusic_idle_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_full_distance",
                        type = "numeric",
                        default_value = 5,
                        range = { 0.5, 50 },
                        decimals_number = 1,
                        title = "elevatormusic_idle_full_distance",
                        tooltip = "elevatormusic_idle_full_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_random_order",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_random_order",
                        tooltip = "elevatormusic_random_order_desc",
                    },
                    {
                        setting_id = "elevatormusic_volume_percent",
                        type = "numeric",
                        default_value = 80,
                        range = { 10, 300 },
                        decimals_number = 0,
                        title = "elevatormusic_volume_percent",
                        tooltip = "elevatormusic_volume_percent_desc",
                    },
                    {
                        setting_id = "elevatormusic_fade_seconds",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 0, 6 },
                        decimals_number = 1,
                        title = "elevatormusic_fade_seconds",
                        tooltip = "elevatormusic_fade_seconds_desc",
                    },
                    {
                        setting_id = "elevatormusic_spatial_rolloff",
                        type = "dropdown",
                        default_value = "exponential",
                        options = {
                            { text = "elevatormusic_spatial_rolloff_linear", value = "linear" },
                            { text = "elevatormusic_spatial_rolloff_log", value = "logarithmic" },
                            { text = "elevatormusic_spatial_rolloff_exp", value = "exponential" },
                            { text = "elevatormusic_spatial_rolloff_none", value = "none" },
                        },
                        title = "elevatormusic_spatial_rolloff",
                        tooltip = "elevatormusic_spatial_rolloff_desc",
                    },
                    {
                        setting_id = "elevatormusic_show_markers",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_show_markers",
                        tooltip = "elevatormusic_show_markers_desc",
                    },
                    {
                        setting_id = "elevatormusic_test_emitter",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_test_emitter",
                        tooltip = "elevatormusic_test_emitter_desc",
                    },
                    {
                        setting_id = "elevatormusic_debug",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_debug",
                        tooltip = "elevatormusic_debug_desc",
                    },
                },
            },
            {
                setting_id = "elevatormusic_visuals_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_visuals_enable",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_visuals_enable",
                        tooltip = "elevatormusic_visuals_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_speed",
                        type = "numeric",
                        default_value = 1.2,
                        range = { 0.1, 7.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_speed",
                        tooltip = "elevatormusic_visuals_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_randomness",
                        type = "numeric",
                        default_value = 0.5,
                        range = { 0, 5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_randomness",
                        tooltip = "elevatormusic_visuals_randomness_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_halo_count",
                        type = "numeric",
                        default_value = 3,
                        range = { 1, 6 },
                        decimals_number = 0,
                        title = "elevatormusic_visuals_halo_count",
                        tooltip = "elevatormusic_visuals_halo_count_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_radius_min",
                        type = "numeric",
                        default_value = 0.65,
                        range = { 0.2, 5.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_radius_min",
                        tooltip = "elevatormusic_visuals_radius_min_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_radius_max",
                        type = "numeric",
                        default_value = 1.00,
                        range = { 0.2, 5.0 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_radius_max",
                        tooltip = "elevatormusic_visuals_radius_max_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_count",
                        type = "numeric",
                        default_value = 12,
                        range = { 4, 24 },
                        decimals_number = 0,
                        title = "elevatormusic_visuals_light_count",
                        tooltip = "elevatormusic_visuals_light_count_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_orbit_variance",
                        type = "numeric",
                        default_value = 0.4,
                        range = { 0, 2 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_light_orbit_variance",
                        tooltip = "elevatormusic_visuals_light_orbit_variance_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_light_vertical_variance",
                        type = "numeric",
                        default_value = 0.6,
                        range = { 0, 4 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_light_vertical_variance",
                        tooltip = "elevatormusic_visuals_light_vertical_variance_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_loop_speed",
                        type = "numeric",
                        default_value = 1.0,
                        range = { 0, 7 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_loop_speed",
                        tooltip = "elevatormusic_visuals_loop_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_spin_randomness",
                        type = "numeric",
                        default_value = 0.5,
                        range = { 0, 5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_spin_randomness",
                        tooltip = "elevatormusic_visuals_spin_randomness_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_show_core",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_visuals_show_core",
                        tooltip = "elevatormusic_visuals_show_core_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_orbit_radius",
                        type = "numeric",
                        default_value = 0.25,
                        range = { 0, 2.5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_orbit_radius",
                        tooltip = "elevatormusic_visuals_orbit_radius_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_orbit_speed",
                        type = "numeric",
                        default_value = 1.0,
                        range = { 0, 10 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_orbit_speed",
                        tooltip = "elevatormusic_visuals_orbit_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_enable",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_visuals_scatter_enable",
                        tooltip = "elevatormusic_visuals_scatter_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_count",
                        type = "numeric",
                        default_value = 6,
                        range = { 1, 28 },
                        decimals_number = 0,
                        title = "elevatormusic_visuals_scatter_count",
                        tooltip = "elevatormusic_visuals_scatter_count_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_distance",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 0.1, 8 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_scatter_distance",
                        tooltip = "elevatormusic_visuals_scatter_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_size_min",
                        type = "numeric",
                        default_value = 0.08,
                        range = { 0.01, 1.0 },
                        decimals_number = 3,
                        title = "elevatormusic_visuals_scatter_size_min",
                        tooltip = "elevatormusic_visuals_scatter_size_min_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_size_max",
                        type = "numeric",
                        default_value = 0.15,
                        range = { 0.01, 2.0 },
                        decimals_number = 3,
                        title = "elevatormusic_visuals_scatter_size_max",
                        tooltip = "elevatormusic_visuals_scatter_size_max_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_speed",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 0, 12 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_scatter_speed",
                        tooltip = "elevatormusic_visuals_scatter_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_hover",
                        type = "numeric",
                        default_value = 0.25,
                        range = { 0, 2 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_scatter_hover",
                        tooltip = "elevatormusic_visuals_scatter_hover_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_sway",
                        type = "numeric",
                        default_value = 0.25,
                        range = { 0, 2 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_scatter_sway",
                        tooltip = "elevatormusic_visuals_scatter_sway_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_scatter_vertical_offset",
                        type = "numeric",
                        default_value = -0.5,
                        range = { -5, 5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_scatter_vertical_offset",
                        tooltip = "elevatormusic_visuals_scatter_vertical_offset_desc",
                    },
                },
            },
        },
    },
}
