local mod = get_mod("ElevatorMusic")

return {
    name = "ElevatorMusic",
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "elevatormusic_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_enable",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_enable",
                        tooltip = "elevatormusic_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_play_activation",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_play_activation",
                        tooltip = "elevatormusic_play_activation_desc",
                    },
                    {
                        setting_id = "elevatormusic_activation_linger",
                        type = "numeric",
                        default_value = 3,
                        range = { 0, 20 },
                        decimals_number = 0,
                        title = "elevatormusic_activation_linger",
                        tooltip = "elevatormusic_activation_linger_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_enabled",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_idle_enabled",
                        tooltip = "elevatormusic_idle_enabled_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_after_activation",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_idle_after_activation",
                        tooltip = "elevatormusic_idle_after_activation_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_distance",
                        type = "numeric",
                        default_value = 10,
                        range = { 4, 30 },
                        decimals_number = 0,
                        title = "elevatormusic_idle_distance",
                        tooltip = "elevatormusic_idle_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_idle_full_distance",
                        type = "numeric",
                        default_value = 4,
                        range = { 1, 20 },
                        decimals_number = 1,
                        title = "elevatormusic_idle_full_distance",
                        tooltip = "elevatormusic_idle_full_distance_desc",
                    },
                    {
                        setting_id = "elevatormusic_random_order",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_random_order",
                        tooltip = "elevatormusic_random_order_desc",
                    },
                    {
                        setting_id = "elevatormusic_volume_percent",
                        type = "numeric",
                        default_value = 120,
                        range = { 10, 300 },
                        decimals_number = 0,
                        title = "elevatormusic_volume_percent",
                        tooltip = "elevatormusic_volume_percent_desc",
                    },
                    {
                        setting_id = "elevatormusic_fade_seconds",
                        type = "numeric",
                        default_value = 1.5,
                        range = { 0, 6 },
                        decimals_number = 1,
                        title = "elevatormusic_fade_seconds",
                        tooltip = "elevatormusic_fade_seconds_desc",
                    },
                    {
                        setting_id = "elevatormusic_spatial_rolloff",
                        type = "dropdown",
                        default_value = "linear",
                        options = {
                            { text = "elevatormusic_spatial_rolloff_linear", value = "linear" },
                            { text = "elevatormusic_spatial_rolloff_log", value = "logarithmic" },
                        },
                        title = "elevatormusic_spatial_rolloff",
                        tooltip = "elevatormusic_spatial_rolloff_desc",
                    },
                    {
                        setting_id = "elevatormusic_show_markers",
                        type = "checkbox",
                        default_value = true,
                        title = "elevatormusic_show_markers",
                        tooltip = "elevatormusic_show_markers_desc",
                    },
                    {
                        setting_id = "elevatormusic_test_emitter",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_test_emitter",
                        tooltip = "elevatormusic_test_emitter_desc",
                    },
                    {
                        setting_id = "elevatormusic_debug",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_debug",
                        tooltip = "elevatormusic_debug_desc",
                    },
                },
            },
            {
                setting_id = "elevatormusic_visuals_group",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "elevatormusic_visuals_enable",
                        type = "checkbox",
                        default_value = false,
                        title = "elevatormusic_visuals_enable",
                        tooltip = "elevatormusic_visuals_enable_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_speed",
                        type = "numeric",
                        default_value = 1.2,
                        range = { 0.1, 6 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_speed",
                        tooltip = "elevatormusic_visuals_speed_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_randomness",
                        type = "numeric",
                        default_value = 0.3,
                        range = { 0, 3 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_randomness",
                        tooltip = "elevatormusic_visuals_randomness_desc",
                    },
                    {
                        setting_id = "elevatormusic_visuals_radius",
                        type = "numeric",
                        default_value = 0.55,
                        range = { 0.2, 1.5 },
                        decimals_number = 2,
                        title = "elevatormusic_visuals_radius",
                        tooltip = "elevatormusic_visuals_radius_desc",
                    },
                },
            },
        },
    },
}
