local mod = get_mod("OrbEmitTest")

return {
    name = "OrbEmitTest",
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "debug_logging",
                type = "checkbox",
                default_value = false,
                title = "debug_logging",
                tooltip = "debug_logging_tooltip",
            },
            {
                setting_id = "orb1_enabled",
                type = "checkbox",
                default_value = false,
                title = "orb1_enabled",
                tooltip = "orb1_tooltip",
            },
            {
                setting_id = "orb1_offset_forward",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb1_offset_forward",
                tooltip = "orb1_offset_forward_tooltip",
            },
            {
                setting_id = "orb1_offset_right",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb1_offset_right",
                tooltip = "orb1_offset_right_tooltip",
            },
            {
                setting_id = "orb1_offset_up",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb1_offset_up",
                tooltip = "orb1_offset_up_tooltip",
            },
            {
                setting_id = "orb2_enabled",
                type = "checkbox",
                default_value = false,
                title = "orb2_enabled",
                tooltip = "orb2_tooltip",
            },
            {
                setting_id = "orb2_show_sphere",
                type = "checkbox",
                default_value = true,
                title = "orb2_show_sphere",
                tooltip = "orb2_show_sphere_tooltip",
            },
            {
                setting_id = "orb2_offset_forward",
                type = "numeric",
                default_value = 7,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb2_offset_forward",
                tooltip = "orb2_offset_forward_tooltip",
            },
            {
                setting_id = "orb2_offset_right",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb2_offset_right",
                tooltip = "orb2_offset_right_tooltip",
            },
            {
                setting_id = "orb2_offset_up",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb2_offset_up",
                tooltip = "orb2_offset_up_tooltip",
            },
            {
                setting_id = "orb3_enabled",
                type = "checkbox",
                default_value = false,
                title = "orb3_enabled",
                tooltip = "orb3_tooltip",
            },
            {
                setting_id = "orb3_show_sphere",
                type = "checkbox",
                default_value = true,
                title = "orb3_show_sphere",
                tooltip = "orb3_show_sphere_tooltip",
            },
            {
                setting_id = "orb3_offset_forward",
                type = "numeric",
                default_value = 3,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb3_offset_forward",
                tooltip = "orb3_offset_forward_tooltip",
            },
            {
                setting_id = "orb3_offset_right",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb3_offset_right",
                tooltip = "orb3_offset_right_tooltip",
            },
            {
                setting_id = "orb3_offset_up",
                type = "numeric",
                default_value = 0,
                range = {-20, 20},
                decimals_number = 1,
                title = "orb3_offset_up",
                tooltip = "orb3_offset_up_tooltip",
            },
        },
    },
}
